#!/usr/bin/env python
import sys
import pilosa

client = pilosa.Client()
schema = client.schema()
index = schema.index("segmentation")
field = index.field("membership")

if len(sys.argv) < 3:
    print("%s <kruxid> <kruxid> [<kruxid>, ...]" % sys.argv[0])
    sys.exit(1)

rows = []
for id in sys.argv[1:]:
    query = field.topn(1, None, 'kruxid', id)
    r = client.query(query).result
    if not r.count_items:
        print("Segment %s not found" % id)
        sys.exit(1)
    rowid = r.count_items[0].id
    rows.append(field.row(rowid))

count = client.query(index.count(index.intersect(*rows))).result.count
print(count)
